steps:
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "rims"
  namespace: "default"
  labels:
    app: "rims"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "rims"
  template:
    metadata:
      labels:
        app: "rims"
    spec:
      containers:
      - name: "rims"
        image: "rims:latest"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "rims-1-hpa-hrcb"
  namespace: "default"
  labels:
    app: "rims-1"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "rims-1"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80