version: '2'
services:
  db:
      image: mariadb:10.1.21
      container_name: yii_mariadb
      restart: always
      volumes:
        - ./mariadb/initdb/:/docker-entrypoint-initdb.d
        - ./mariadb/data/:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=RXbNkA6Ysk3cM7Eo
        - MYSQL_DATABASE=yiidb
        - MYSQL_USER=yii
        - MYSQL_PASSWORD=iFvJMyjZp1EnlQvR
      command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci

  php:
      build: ./php
      container_name: yii_php7-fpm
      restart: always
      volumes:
        - ./www/:/var/www/html
        - ./php/php-fpm.conf:/usr/local/etc/php-fpm.conf
        - ./php/php.ini:/usr/local/etc/php/php.ini
        - ./logs/php-fpm:/var/log/php-fpm
      expose:
        - "9000"

  nginx:
      image: nginx:1.11.9-alpine
      container_name: yii_nginx
      restart: always
      volumes:
        - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
        - ./nginx/conf.d:/etc/nginx/conf.d:ro
        - ./logs/nginx:/var/log/nginx
      volumes_from:
        - php
      ports:
        - 8080:80

  mya:
    image: phpmyadmin/phpmyadmin
    container_name: yii_phpmyadmin
    restart: always
    ports:
      - "8000:80"